### ISSUE TITLE
Remove conda default channel from YML

### ISSUE THREAD

**Issue by fatipardo** [fatipardo/PDBClean-0.0.2#121]
Make sure installation is not affected by removing the channel

**Comment by fatipardo** [comment]
Our solution was not enough. Conda automatically adds default channel. 
Can we try:
conda config --remove channels defaults
next time we install PDBClean? 
@gdkwxn

**Comment by gdkwxn** [comment]
<img width="1440" alt="FIRST STEPS" src="https://github.com/user-attachments/assets/1b431f0a-8cec-4553-953d-759cab670413">

The red box contains the error message. The error message is due to me running the line 
"conda config --remove channels defaults"
before hand. That error message confirms that it did what it had to do I believe. 

Everything above the cyan line is just the environment being created. When i opened the environment.yml file before installation, it didn't contain the default channel. After completely installing PDBCleanV2, it still didn't contain the default channel.

**Comment by fatipardo** [comment]
This is great! Thanks for testing it. Before we close this issue, let's include this step in our installation instructions. Can you modify our README @gdkwxn ?
